#!/usr/bin/env python3
"""
Generates reference/SUZUKI_PROTOCOL_REFERENCE.md from the JSON catalogs produced by
extract_fields.py (suzuki-fields-catalog.json, suzuki-dtc-codes.json). Run this after
regenerating either catalog to keep the human-readable doc in sync.

Usage: python3 generate_reference_doc.py <catalog.json> <dtc-codes.json> <output.md>
"""
import json
import sys
from collections import defaultdict
from pathlib import Path


def main():
    catalog_path, dtc_path, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    fields = json.loads(Path(catalog_path).read_text())
    dtc_codes = json.loads(Path(dtc_path).read_text())

    by_module = defaultdict(list)
    for f in fields:
        module = f["id"].split(".", 1)[0]
        by_module[module].append(f)

    lines = []
    lines.append("# Suzuki protocol reference (extracted from decompiled sz-viewer sources)")
    lines.append("")
    lines.append(
        "Generated by `reference/generate_reference_doc.py` from "
        "`core/src/jvmMain/resources/suzuki-fields-catalog.json` and `suzuki-dtc-codes.json`, "
        "which are themselves produced by `reference/extract_fields.py` parsing the CFR-decompiled "
        "`sz-viewer.jar`. This is a structural extraction (byte offsets, scale/offset, request "
        "addressing) — labels/units are read directly from decompiled source, but exact request "
        "framing for some CAN/Jeep-platform ECU variants is unresolved (see the `verified` column). "
        "Always confirm against a real vehicle before trusting a specific field/value.",
    )
    lines.append("")
    lines.append(f"- **{len(fields)}** live-data fields across **{len(by_module)}** modules")
    lines.append(f"- **{len(dtc_codes)}** Suzuki DTC codes with descriptions")
    lines.append("")
    lines.append("## Table of contents")
    lines.append("")
    for module in sorted(by_module):
        anchor = module.lower()
        lines.append(f"- [{module}](#{anchor}) ({len(by_module[module])} fields)")
    lines.append("- [DTC codes](#dtc-codes)")
    lines.append("")

    lines.append("## Live-data fields by module")
    lines.append("")
    for module in sorted(by_module):
        lines.append(f"### {module}")
        lines.append("")
        lines.append("| Field | Unit | Request (target/mode/params) | Decode (skip/len/signed/scale/offset) | Verified | Source |")
        lines.append("|---|---|---|---|---|---|")
        for f in sorted(by_module[module], key=lambda x: x["id"]):
            req = f["request"]
            dec = f["decode"]
            req_str = f"0x{req['targetAddress']:02X} / 0x{req['mode']:02X} / {req['params']}"
            dec_str = f"{dec['skipBytes']} / {dec['byteLength']} / {dec['signed']} / {dec['scale']} / {dec['offset']}"
            verified = "\u2713" if f.get("verified") else "?"
            source = f.get("sourceClass", "").rsplit(".", 1)[-1]
            lines.append(f"| {f['label']} (`{f['id']}`) | {f['unit']} | {req_str} | {dec_str} | {verified} | {source} |")
        lines.append("")

    lines.append("## DTC codes")
    lines.append("")
    lines.append(
        "Format: standard SAE J2012 (P/C/B/U + 4 hex digits). Descriptions are Suzuki's own, "
        "extracted from `com.malykh.szviewer.common.dtc.code.suzuki.SuzukiCodeTextPredefined$`.",
    )
    lines.append("")
    lines.append("| Code | Description |")
    lines.append("|---|---|")
    for code in sorted(dtc_codes):
        desc = dtc_codes[code]["description"].replace("|", "\\|")
        lines.append(f"| {code} | {desc} |")
    lines.append("")

    Path(out_path).write_text("\n".join(lines))
    print(f"Wrote {out_path}: {len(fields)} fields, {len(dtc_codes)} DTC codes", file=sys.stderr)


if __name__ == "__main__":
    main()
